[[section-design-decisions]]
== Architekturentscheidungen
:toc: right
:toclevels: 3

== Einführung

In diesem Dokument werden die wichtigsten Architekturentscheidungen für das Projekt "FLOW" erfasst.
Jede Entscheidung wird ausführlicher in einem eigenen Unterkapitel behandelt.

== Übersicht der Entscheidungen

[options="header"]

- Entscheidung von Technologie für Benutzerschnittstelle und Interaktion
* [line-through]#RFID-Reader#
* Touch Display
* Knopf

[role="architectural-decision"]
=== Technologie für Benutzerschnittstelle und Interaktion

==== Kontext

Als Hauptinteraktion in dem Produkt "FLOW" interagiert der Spieler mit den Edges des Graphen (mehr zum Spiel unter Kapitel 1):
Der Spieler kann den Flow, welcher durch die Edges fliesst, verändern, dies ist limitiert durch die maximale Kapazität der Edges. Das Verändern des Fluss durch ein Edge ist ein Hauptbestandteil des Spiels und gleichzeitig die, am häufigsten vorkommende Interaktion.

==== Entscheidung

Wir wollen sicherstellen, dass die gewählte Technologie für die Benutzerinteraktion möglichst einfach zu bedienen und intuitiv ist. Die Schnittstelle muss augenblicklich und unmerklich schnell abfolgen. Es muss sichergestellt werden, dass alle Personen unserer Zielgruppe, Jugendliche von 12-17 Jahren, das Produkt verwenden können. Die verwendete Technologie muss schon etabliert sein, um die technische Schuld möglichst realistisch zu behalten.

==== Status

Das Projekt verwendet den Touch Display mit je einem Knopf pro Edge. Somit kann der Benutzer eine Edge mit einem Knopf anwählen und anschliessend einen Wert über den Touch Display zuweisen.
Die ursprüngliche Version des Spiels beinhaltete nur RFID-Reader, welche, entlang der Edges verbaut geworden wären.
Begründet wurde dies mit der einfachen und intuitiven Anwendung für den Benutzer und der bereits zahlreich existierenden Implementationen der RFID Technologie. Zudem existieren für die vorgegebene Library Pi4j Beispielprojekte.
Die geplante Verwendung von RFID-Reader entlang der Edges des Graphen hatte eine Kaskade von technischen Komplikationen zur Folge:

.RFID Interference:
Mögliche Störung der Leseprozesse der RFID Reader, bei zu vielen und zu nah aneinanderliegenden Komponenten.

.Komplexitätszunahme der Hardware Architektur:
Das Verwalten und Ansprechen von über 20 RFID Readern erhöht die technischen Schulden schwerwiegend.
Um die technischen Schulden verkraften zu können, musste ein Grossteil der Interaktion auf Knöpfe verlegt werden. Diese sind ebenfalls einfach zu bedienen, brauchen aber deutlich weniger technischen Aufwand:

.Weniger Verkabelung:
Statt 4 Kabel per Reader nur 2 per Knopf.
Dies vereinfacht das Ersetzen der entsprechenden Komponente und die Verkabelung als Ganzes.

.Weniger komplexe Kommunikation:
Es gibt nur eine Interaktion, nämlich das Betätigen des Knöpfe. Leseoperationen folgen immer durch den gleichen RFID-Reader.

.Einfachere Fehlerbehebung:
Im Falle eines Defekts ist es einfacher, einen einzelnen Knopf auszutauschen, als einen RFID-Reader zu ersetzen. Zudem sind die Kosten für Ersatzteile bei Knöpfe geringer.

.Skalierbarkeit:
Die Verwendung von Knöpfe ermöglicht es, das Projekt einfacher zu erweitern, da sie weniger Platz beanspruchen und kostengünstiger sind als RFID-Reader.

.Energieeffizienz:
Knöpfe verbrauchen weniger Energie als RFID-Reader, was zu einer übersichtlicheren Stromversorgung des Gesamtsystems führt und gleichzeitig die Umweltbelastung verringert.

.Intuitive Lösung für Benutzer, insbesondere Kinder:
Knöpfe sind eine vertraute und einfach zu verstehende Interaktionsmethode für Benutzer aller Altersgruppen, insbesondere für Kinder. Dies fördert die Akzeptanz bei der Zielgruppe.

[role="architectural-decision"]
=== RFID-Reader und Knöpfe

==== Kontext

Der Touch Display und Knöpfe sind entscheidende Elemente der Benutzerschnittstelle des Projekts "FLOW". Sie ermöglichen die Interaktion des Benutzers mit den Edges und die Anpassung des Flusses.

==== Entscheidung

Die Entscheidung wurde getroffen, keine RFID-Reader und stattdessen Knöpfe für jede Edge zu verwenden und dies mit einem Touch Display zu kombinieren.
Dies wurde als der beste Kompromiss zwischen Benutzerfreundlichkeit, technischer Komplexität und Kosten angesehen.

==== Status

Die Umsetzung dieser Entscheidung ist bereits im Gange. Die Verwendung eines zentralen RFID-Readers und Knöpfe für jede Edge wird voraussichtlich die technische Komplexität reduzieren und ermöglicht eine einfachere Skalierung des Projekts.

[role="architectural-decision"]
=== Verwendung von etablierten Technologien

==== Kontext

Um die technische Schuld des Projekts "FLOW" in Grenzen zu halten, ist es wichtig, etablierte Technologien zu verwenden. Dies ermöglicht eine leichtere Integration mit bestehenden Systemen und fördert die Akzeptanz bei der Zielgruppe.

==== Entscheidung

Die Entscheidung wurde getroffen, Technologien zu verwenden, die weit verbreitet sind, wie z. B. RFID-Technologie und Knöpfe. Das Requirement der Programmiersprache Java ist jedoch beibehalten, was für die Implementierung eine Rolle spielt.

==== Status

Die Verwendung etablierter Technologien ist derzeit im Projekt in Arbeit. Obwohl die gewählten Technologien weit verbreitet sind, besteht die Herausforderung darin, dass wenig Code in Java verfügbar ist. Dies hat dazu geführt, dass das Team bei der jetzigen Umsetzung der Library und
der I2C-Schnittstelle auf einige Probleme gestossen ist. Trotz dieser Herausforderungen ermöglicht die Nutzung etablierter Technologien eine Verringerung der technischen Schuld und die Verbesserung der Akzeptanz bei der Zielgruppe, sobald die Umsetzung abgeschlossen ist.

[role="arc42help"]
////
****
.Inhalt
Wichtige, teure, große oder riskante Architektur- oder Entwurfsentscheidungen inklusive der jeweiligen Begründungen.
Mit "Entscheidungen" meinen wir hier die Auswahl einer von mehreren Alternativen unter vorgegebenen Kriterien.

Wägen Sie ab, inwiefern Sie Entscheidungen hier zentral beschreiben, oder wo eine lokale Beschreibung (z.B. in der Whitebox-Sicht von Bausteinen) sinnvoller ist.
Vermeiden Sie Redundanz.
Verweisen Sie evtl. auf Abschnitt 4, wo schon grundlegende strategische Entscheidungen beschrieben wurden.

.Motivation
Stakeholder des Systems sollten wichtige Entscheidungen verstehen und nachvollziehen können.

.Form
Verschiedene Möglichkeiten:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) für jede wichtige Entscheidung
* Liste oder Tabelle, nach Wichtigkeit und Tragweite der Entscheidungen geordnet
* ausführlicher in Form einzelner Unterkapitel je Entscheidung

.Weiterführende Informationen

Siehe https://docs.arc42.org/section-9/[Architekturentscheidungen] in der arc42 Dokumentation (auf Englisch!).
Dort finden Sie Links und Beispiele zum Thema ADR.

****
////